// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH9A4mxNvTtgbL2kf1Dr4tCj5JdVpcPfw',
    appId: '1:1085571193268:web:08189a9bc1154d5ea5bae1',
    messagingSenderId: '1085571193268',
    projectId: 'gradready-5033e',
    authDomain: 'gradready-5033e.firebaseapp.com',
    storageBucket: 'gradready-5033e.firebasestorage.app',
    measurementId: 'G-LLL1VR5NZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJpbKQpXZ9VLXloGr1vIOX3tjy4CbEUc0',
    appId: '1:1085571193268:android:c9e9b0caba39b5a0a5bae1',
    messagingSenderId: '1085571193268',
    projectId: 'gradready-5033e',
    storageBucket: 'gradready-5033e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTYf9SFzWNFfoL5NpGq2QwBTE4TijtuGs',
    appId: '1:1085571193268:ios:c9ba9f3685694897a5bae1',
    messagingSenderId: '1085571193268',
    projectId: 'gradready-5033e',
    storageBucket: 'gradready-5033e.firebasestorage.app',
    iosBundleId: 'com.example.gradReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTYf9SFzWNFfoL5NpGq2QwBTE4TijtuGs',
    appId: '1:1085571193268:ios:c9ba9f3685694897a5bae1',
    messagingSenderId: '1085571193268',
    projectId: 'gradready-5033e',
    storageBucket: 'gradready-5033e.firebasestorage.app',
    iosBundleId: 'com.example.gradReady',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH9A4mxNvTtgbL2kf1Dr4tCj5JdVpcPfw',
    appId: '1:1085571193268:web:55b62bc35765314ba5bae1',
    messagingSenderId: '1085571193268',
    projectId: 'gradready-5033e',
    authDomain: 'gradready-5033e.firebaseapp.com',
    storageBucket: 'gradready-5033e.firebasestorage.app',
    measurementId: 'G-F805MB9VN0',
  );
}
